# Generated by Django 3.2.9 on 2022-03-18 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0005_alter_broadcastnotification_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
