# Generated by Django 3.2.9 on 2022-03-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0006_broadcastnotification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastnotification',
            name='sent',
        ),
    ]
