# Generated by Django 3.2.9 on 2021-12-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
