# Generated by Django 3.2.9 on 2022-01-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0003_vehicleinspectionreport_repairstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='engine_desc',
            field=models.CharField(default='', max_length=240, verbose_name='Engine Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='enginge_fix',
            field=models.CharField(default='', max_length=240, verbose_name='Engine Fix'),
        ),
    ]
