# Generated by Django 3.2.9 on 2022-01-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0004_auto_20220118_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleinspectionreport',
            old_name='enginge_fix',
            new_name='engine_fix',
        ),
    ]
