# Generated by Django 3.2.9 on 2022-01-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0006_vehicleinspectionreport_engine_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='assignedMech',
            field=models.CharField(default='', max_length=120, verbose_name='Assigned Mechanic'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='lastUpdatedMech',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='lastUpdatedUser',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
