# Generated by Django 3.2.9 on 2022-01-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_app', '0008_auto_20220119_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVehicleInspectionReport',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('truck', models.CharField(max_length=120, verbose_name='Truck Number')),
                ('assignedMech', models.CharField(default='', max_length=120, verbose_name='Assigned Mechanic')),
                ('repairStatus', models.BooleanField(default=False)),
                ('lastUpdatedUser', models.DateField(blank=True, null=True)),
                ('lastUpdatedMech', models.DateField(blank=True, null=True)),
                ('engine_check', models.BooleanField(default=False)),
                ('engine_desc', models.CharField(default='', max_length=240, verbose_name='Engine Description')),
                ('engine_fix', models.CharField(default='', max_length=240, verbose_name='Engine Fix')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vehicle inspection report',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
