# Generated by Django 3.2.9 on 2022-01-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0009_historicalvehicleinspectionreport'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalvehicleinspectionreport',
            table='vehicleinspectionreport_history',
        ),
    ]
