# Generated by Django 3.2.9 on 2022-01-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0011_alter_historicalvehicleinspectionreport_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='lastUpdatedMech',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='lastUpdatedUser',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='lastUpdatedMech',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='lastUpdatedUser',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
