# Generated by Django 3.2.9 on 2022-01-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0012_auto_20220120_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalVehicleInspectionReport',
        ),
    ]
