# Generated by Django 3.2.9 on 2022-02-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0002_auto_20220204_1427'),
        ('driver_app', '0015_auto_20220204_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='equipment',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment_app.equipment'),
        ),
        migrations.RemoveField(
            model_name='vehicleinspectionreport',
            name='equipment',
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipment_app.equipment'),
        ),
    ]
