# Generated by Django 3.2.9 on 2022-02-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0002_auto_20220204_1427'),
        ('driver_app', '0016_auto_20220204_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='equipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment_app.equipment'),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_app.equipment'),
        ),
    ]
