# Generated by Django 3.2.9 on 2022-02-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0017_auto_20220204_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='equipment',
            field=models.CharField(default='', max_length=120, verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='equipment',
            field=models.CharField(default='', max_length=120, verbose_name='Equipment'),
        ),
    ]
