# Generated by Django 3.2.9 on 2022-02-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0018_auto_20220207_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='air_lines_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='air_lines_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Air Lines Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='air_lines_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Air Lines Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='brakes_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='brakes_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Brakes Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='brakes_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Brakes Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='coupling_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='coupling_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Coupling Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='coupling_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Coupling Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='emergency_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='emergency_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='transmission Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='emergency_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='transmission Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='emergency_type',
            field=models.CharField(choices=[('AID', 'First Aid'), ('EXT', 'Fire Extinguisher'), ('TRI', 'Triangles')], default='AID', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='horn_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='horn_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Horn Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='horn_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Horn Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='lights_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='lights_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Lights Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='lights_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Lights Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='lights_type',
            field=models.CharField(choices=[('R', 'Running'), ('S', 'Signal'), ('B', 'Brakes')], default='B', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='mirrors_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='mirrors_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Mirrors Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='mirrors_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Mirrors Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='other_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='other_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Other Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='other_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Other Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='steering_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='steering_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Steering Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='steering_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Steering Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='tires_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='tires_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Tires Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='tires_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Tires Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='transmission_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='transmission_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Transmission Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='transmission_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Transmission Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='wheels_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='wheels_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Wheels Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='wheels_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Wheels Fix'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='wipers_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='wipers_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Wipers Description'),
        ),
        migrations.AddField(
            model_name='historicalvehicleinspectionreport',
            name='wipers_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Wipers Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='air_lines_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='air_lines_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Air Lines Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='air_lines_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Air Lines Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='brakes_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='brakes_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Brakes Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='brakes_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Brakes Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='coupling_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='coupling_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Coupling Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='coupling_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Coupling Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='emergency_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='emergency_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='transmission Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='emergency_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='transmission Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='emergency_type',
            field=models.CharField(choices=[('AID', 'First Aid'), ('EXT', 'Fire Extinguisher'), ('TRI', 'Triangles')], default='AID', max_length=3),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='horn_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='horn_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Horn Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='horn_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Horn Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='lights_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='lights_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Lights Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='lights_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Lights Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='lights_type',
            field=models.CharField(choices=[('R', 'Running'), ('S', 'Signal'), ('B', 'Brakes')], default='B', max_length=3),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='mirrors_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='mirrors_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Mirrors Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='mirrors_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Mirrors Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='other_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='other_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Other Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='other_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Other Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='steering_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='steering_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Steering Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='steering_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Steering Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='tires_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='tires_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Tires Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='tires_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Tires Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='transmission_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='transmission_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Transmission Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='transmission_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Transmission Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='wheels_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='wheels_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Wheels Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='wheels_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Wheels Fix'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='wipers_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='wipers_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Wipers Description'),
        ),
        migrations.AddField(
            model_name='vehicleinspectionreport',
            name='wipers_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Wipers Fix'),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='engine_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Engine Description'),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='engine_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Engine Fix'),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='engine_desc',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Engine Description'),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='engine_fix',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Engine Fix'),
        ),
    ]
