# Generated by Django 3.2.9 on 2022-02-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0019_auto_20220217_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='air_lines_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='air_lines_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='brakes_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='brakes_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='coupling_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='coupling_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='emergency_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='emergency_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='engine_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='engine_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='horn_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='horn_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='lights_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='lights_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='mirrors_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='mirrors_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='other_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='other_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='steering_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='steering_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='tires_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='tires_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='transmission_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='transmission_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='wheels_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='wheels_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='wipers_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='wipers_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='air_lines_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='air_lines_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='brakes_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='brakes_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='coupling_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='coupling_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='emergency_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='emergency_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='engine_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='engine_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='horn_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='horn_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='lights_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='lights_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='mirrors_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='mirrors_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='other_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='other_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='steering_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='steering_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='tires_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='tires_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='transmission_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='transmission_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='wheels_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='wheels_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='wipers_desc',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='wipers_fix',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
