# Generated by Django 3.2.9 on 2022-03-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0006_equipment_predicted_mileage'),
        ('driver_app', '0020_auto_20220217_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicleinspectionreport',
            name='equipment',
            field=models.ForeignKey(blank=True, db_constraint=False, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment_app.equipment'),
        ),
        migrations.AlterField(
            model_name='vehicleinspectionreport',
            name='equipment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='equipment_app.equipment'),
        ),
    ]
