# Generated by Django 3.2.9 on 2022-02-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('TCK', 'Truck'), ('TR', 'Trailer')], default='Truck', max_length=3),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment',
            field=models.IntegerField(default='Null', verbose_name='Equipment Number'),
        ),
    ]
