# Generated by Django 3.2.9 on 2022-02-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0002_auto_20220204_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('TCK', 'Truck'), ('TR', 'Trailer')], default='TRK', max_length=3),
        ),
    ]
