# Generated by Django 3.2.9 on 2022-03-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0003_alter_equipment_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Trailer', 'Trailer')], default='Truck', max_length=20),
        ),
    ]
