# Generated by Django 3.2.9 on 2022-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0004_alter_equipment_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='mileage',
            field=models.IntegerField(default='0'),
        ),
    ]
