# Generated by Django 3.2.9 on 2022-03-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0005_equipment_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='predicted_mileage',
            field=models.IntegerField(default='0'),
        ),
    ]
